"""
Kanal ayarları - tüm 12 kanalın yapılandırması burada.
"""

CHANNELS = {
    "coding": {
        "display_name": "Music for Coding and Focus",
        "channel_id": "UCkVKKmob42pgVahy7iN8dJg",
        "drive_folder_id": "1ZGDsj91rLyAn53QADHF-XB4nk63_VWYL",
        "clips_folder_id": "1WS1MCEihIQXlhldY2-CYodDpu2ls5hBb",
        "drive_account": "hesap98",
        "youtube_account": "hesap98",
        "concept": "lofi hip hop study music",
        "crossfade_seconds": 4,
        "video_keywords": ["lofi", "study music", "chill beats", "coding music", "focus music"],
        "seo_keywords": [
            "late night coding session music",
            "rainy lofi cafe ambience",
            "lofi for programmers focus",
            "1 hour coding music no ads",
            "midnight study lofi mix",
            "deep work lofi beats",
            "cozy coffee shop lofi",
            "study with me lofi rain",
            "lofi for software engineers",
            "lofi study session 2026",
            "focus music for coding deep work",
            "chill beats for late night work",
            "lofi hip hop study beats playlist",
            "coffee shop ambience study music",
            "night owl coding lofi playlist",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "SpaceGrotesk-Bold.ttf",
        "thumbnail_texts": ["DEEP FOCUS", "CODE MODE", "FOCUS", "STUDY SESSION", "LOCK IN"],
        "short_sentences": [
            "Your best code is written in silence.",
            "Coffee. Lo-fi. Terminal. Repeat.",
            "Deep work begins when world goes quiet.",
            "2 AM and you're in the zone.",
            "Focus is not a talent. It's a habit.",
            "Debug mode: music on, world off.",
            "Ship it. But first, lock in.",
            "One tab open. Zero distractions.",
        ],
        "short_quotes": [
            "First, solve the problem. — John Johnson",
            "Simplicity is efficiency. — Austin Freeman",
            "Focus on what you won't do. — Carmack",
            "The scariest moment is before you start. — King",
        ],
    },
    "zen": {
        "display_name": "Zen Yoga Music",
        "channel_id": "UCwCgjS5hnrIcnbgDTT6w59Q",
        "drive_folder_id": "1bk6DFdWy0s_WCoIMBN_wfotFeBpTM9_2",
        "clips_folder_id": "12bTsKRMLJxQrF0XpvXL7gBpc8q3QJZ7d",
        "drive_account": "hesap98",
        "youtube_account": "hesap98",
        "concept": "zen meditation tibetan ambient",
        "crossfade_seconds": 8,
        "video_keywords": ["yoga music", "meditation", "zen", "tibetan", "peaceful music"],
        "seo_keywords": [
            "tibetan singing bowls 1 hour deep healing",
            "morning yoga flow gentle music",
            "zen meditation rain forest sounds",
            "yoga nidra deep sleep music",
            "balance meditation music inner peace",
            "shamanic drumming meditation 1 hour",
            "japanese zen garden ambience music",
            "hatha yoga calming background music",
            "mindfulness meditation 1 hour relaxing",
            "forest bathing meditation nature sounds",
            "bedtime yoga relaxation gentle music",
            "stress relief meditation tibetan bowls",
            "deep meditation music for spiritual healing",
            "kundalini yoga awakening music",
            "calming yoga music for beginners",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "CormorantGaramond-Bold.ttf",
        "thumbnail_texts": ["Tibetan Bowls", "Inner Peace", "Zen Yoga", "Deep Calm", "Morning Zen"],
        "short_sentences": [
            "Still the mind. Free the soul.",
            "Breathe in peace. Breathe out tension.",
            "Your mat is your sanctuary.",
            "Peace is not found. It is practiced.",
            "Soften. Surrender. Release.",
            "Return to yourself, again and again.",
            "There is nowhere to go. You are home.",
            "In silence, you are whole.",
        ],
        "short_quotes": [
            "Peace comes from within. — Buddha",
            "You are the sky. — Pema Chödrön",
            "The quieter you become. — Ram Dass",
            "Yoga is the journey to the self.",
        ],
    },
    "vault": {
        "display_name": "Millionaire Vault",
        "channel_id": "UCpMMN35Cp_DBCyoVJY1R3tw",
        "drive_folder_id": "1ysfqX-UsbTOqX8jE9AZJ1HEb0NNWMSOM",
        "clips_folder_id": "1CJWOvaDl4W-RH0sQBPJXvQ2kgi_iBwZT",
        "drive_account": "hesap97",
        "youtube_account": "hesap97",
        "concept": "dark cinematic trap motivational",
        "crossfade_seconds": 3,
        "video_keywords": ["motivation music", "dark trap", "sigma", "grindset", "hustle"],
        "seo_keywords": [
            "dark trap motivation 1 hour",
            "sigma male grindset music",
            "alpha workout dark beats playlist",
            "millionaire mindset hustle music",
            "lock in mode dark phonk",
            "late night gym motivation trap",
            "ceo morning motivation dark beats",
            "drive home dark trap mix",
            "3 am hustler motivation music",
            "no excuses workout music dark",
            "money mindset dark beats",
            "sigma rules motivation playlist",
            "dark phonk gym workout 2026",
            "high value man motivation music",
            "boss energy dark trap mix",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "BebasNeue-Regular.ttf",
        "thumbnail_texts": ["GRINDSET", "LOCK IN", "NO EXCUSES", "MILLIONAIRE"],
        "short_sentences": [
            "While they sleep, you grind.",
            "Discipline is the new rich.",
            "The weak rest. The hungry execute.",
            "No shortcuts. No excuses. No limits.",
            "Lock in. The world owes you nothing.",
            "Pain today. Legacy tomorrow.",
            "Outwork everyone. Every single day.",
            "Most want success. Few pay for it.",
        ],
        "short_quotes": [
            "Discipline equals freedom. — Jocko",
            "Pray for strength. — Bruce Lee",
            "He who has a why. — Nietzsche",
            "Move mountains. Start small. — Confucius",
        ],
    },
    "chakra": {
        "display_name": "Chakra Healing Meditation",
        "channel_id": "UCVnJG9DB4jYpv4PMSJvkuIA",
        "drive_folder_id": "1P7O2FBPApSXNjn3JjWzi_GlFDdAoDhYq",
        "clips_folder_id": "1y22dntgRRAtzwt5TP0Ag-w9knmlrmL2n",
        "drive_account": "hesap97",
        "youtube_account": "hesap97",
        "concept": "chakra healing solfeggio frequency",
        "crossfade_seconds": 10,
        "video_keywords": ["chakra healing", "432hz", "528hz", "meditation music", "sound healing"],
        "seo_keywords": [
            "528 Hz love frequency heart chakra",
            "432 Hz deep healing meditation music",
            "741 Hz throat chakra cleanse meditation",
            "396 Hz root chakra grounding music",
            "639 Hz heart chakra love attraction",
            "852 Hz third eye awakening meditation",
            "963 Hz crown chakra divine connection",
            "417 Hz solar plexus power chakra",
            "all 7 chakras balance meditation 1 hour",
            "chakra clearing negative energy removal",
            "solfeggio frequency anxiety relief",
            "chakra healing music sleep meditation",
            "chakra alignment morning meditation",
            "balancing chakras for beginners guided",
            "deep chakra cleansing solfeggio frequencies",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "Marcellus-Regular.ttf",
        "thumbnail_texts": ["Chakra Healing", "528 Hz", "432 Hz", "Frequency Healing", "Sacred Sounds"],
        "short_sentences": [
            "528 Hz — frequency of love.",
            "Your energy centers align now.",
            "Sound is the oldest medicine.",
            "Vibrate higher. Always.",
            "Balance begins from inside.",
            "Ancient frequencies. Modern healing.",
            "Release what blocks you.",
            "You are energy. You are light.",
        ],
        "short_quotes": [
            "Energy, frequency, vibration. — Tesla",
            "The wound is where light enters. — Rumi",
            "Energy flows where attention goes.",
            "Healing others heals yourself.",
        ],
    },
    "beach": {
        "display_name": "Beach Club Beats",
        "channel_id": "UC9AcTTuosbZ17P0F0tfMg3g",
        "drive_folder_id": "1S0f5ojyNWHSb8K7RGkwBrcn1vxn1Jnco",
        "clips_folder_id": "1c11dVr0S_cEK5hlxIIQlf_fzor03Mq0O",
        "drive_account": "hesap99",
        "youtube_account": "hesap99",
        "concept": "tropical house beach club",
        "crossfade_seconds": 4,
        "video_keywords": ["beach music", "tropical house", "summer vibes", "ibiza", "deep house"],
        "seo_keywords": [
            "ibiza pool party house mix 2026",
            "tropical house summer beach club",
            "miami beach deep house mix",
            "boat party house music summer",
            "vacation vibes tropical mix 2026",
            "poolside house beats afternoon",
            "sunset beach club mix tropical",
            "tropical deep house lounge",
            "caribbean beach house mix",
            "tulum beach club beats sunset",
            "summer beach house party 2026",
            "tropical poolside chill house mix",
            "beach club afternoon house mix",
            "balearic beach house ibiza vibes",
            "tropical house workout summer mix",
        ],
        "thumbnail_style": "clean",
        "thumbnail_font": "",
        "thumbnail_texts": [],
        "short_sentences": [
            "The ocean called. You answered.",
            "Salt air. Bare feet. Good music.",
            "Every wave is an invitation.",
            "Blue water. Warmer music.",
            "No plans. Just music and ocean.",
            "Life is short. The playlist is long.",
            "Sand in toes. Bass in soul.",
            "Summer doesn't end here.",
        ],
        "short_quotes": [
            "Live in the sunshine. — Emerson",
            "The sea casts its spell. — Cousteau",
            "I am only a child on the beach. — Newton",
        ],
    },
    "summer": {
        "display_name": "Summer House Music",
        "channel_id": "UC1w2S1apy3UK-pRaIEJBavA",
        "drive_folder_id": "15jR06ZQXUbUb3uk08BHEhwfsLrpr2yEh",
        "clips_folder_id": "1LiywuL07wnWcXM-C0vIwixnV5ztFfBsz",
        "drive_account": "hesap99",
        "youtube_account": "hesap99",
        "concept": "deep house summer mediterranean",
        "crossfade_seconds": 4,
        "video_keywords": ["deep house", "summer house", "mediterranean", "lounge", "chillout"],
        "seo_keywords": [
            "rooftop sunset deep house mix",
            "mediterranean lounge deep house",
            "santorini sunset house music",
            "italian villa chillout vibes",
            "yacht deep house sunset mix",
            "mykonos lounge beats sunset",
            "amalfi coast deep house chill",
            "golden hour rooftop deep house mix",
            "ibiza sunset deep house lounge",
            "luxury hotel lobby chillout mix",
            "monaco sunset deep house lounge",
            "saint tropez deep house mix",
            "cote dazur summer house mix",
            "elegant deep house dinner party",
            "mediterranean villa chillout 2026",
        ],
        "thumbnail_style": "clean",
        "thumbnail_font": "",
        "thumbnail_texts": [],
        "short_sentences": [
            "The golden hour needs a golden track.",
            "Luxury is not a place. It's a feeling.",
            "Wine. View. Music. In that order.",
            "Rooftop. Skyline. Volume up.",
            "Slow down. This is the good part.",
            "Time moves differently here.",
            "Summer light. Summer soul.",
            "Mediterranean air hits different.",
        ],
        "short_quotes": [
            "To travel is to live. — Andersen",
            "Fill life with experiences.",
            "The world is a book. — Augustine",
        ],
    },
    "pets": {
        "display_name": "Relaxing Dogs and Cats",
        "channel_id": "UCyYCN2hqzJBSA9XNes1Shig",
        "drive_folder_id": "1eY8y0RDewp0lA5fjLuDuvZErOxUnUIW-",
        "clips_folder_id": "1r5YJxeY2s81BZJ-dAqbe8Y-0hgCFh_jf",
        "drive_account": "hesap87",
        "youtube_account": "hesap87",
        "concept": "soft acoustic for pets calm",
        "crossfade_seconds": 6,
        "video_keywords": ["dog music", "cat music", "pet relaxation", "calm pets", "anxiety music"],
        "seo_keywords": [
            "music for dogs home alone anxiety",
            "calming music for stressed cats",
            "puppy sleep music for first night",
            "music for anxious dogs separation",
            "vet recommended dog calming music",
            "music to calm aggressive dogs barking",
            "music for cats during car ride",
            "calm music for new kittens",
            "music for dogs with thunderstorm phobia",
            "music for new puppy first night home",
            "stress relief music for cats anxiety",
            "music for senior dogs sleep peaceful",
            "calm music for rescue dogs adoption",
            "music for dogs while owner away",
            "soothing music for anxious cats vet",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "Nunito-ExtraBold.ttf",
        "thumbnail_texts": ["Calm Pets", "Dog Relax", "Cat Sleep", "Home Alone", "Anxious Pets"],
        "short_sentences": [
            "You're not alone, buddy.",
            "Calm vibes for your best friend.",
            "They can hear the love.",
            "Soft music. Safe space.",
            "For the ones who wait by the door.",
            "Home alone? Not anymore.",
            "They give everything. Give them this.",
            "Safe sounds for sensitive souls.",
        ],
        "short_quotes": [
            "Animals ask no questions. — Eliot",
            "Love an animal, wake your soul.",
            "Treat animals well. — Gandhi",
        ],
    },
    "breathe": {
        "display_name": "Breathe and Chill",
        "channel_id": "UCqBZrQuzsfp8_sTRu97T3VA",
        "drive_folder_id": "1ivZr7goxS7VJpMwyLqwCkP1hcezievW-",
        "clips_folder_id": "17pRNXvwn2NXYHf9zX-g6fxRrwpSesO_N",
        "drive_account": "hesap87",
        "youtube_account": "hesap87",
        "concept": "breathing meditation 4-7-8",
        "crossfade_seconds": 8,
        "video_keywords": ["breathing exercise", "4-7-8 breathing", "meditation", "calm music", "anxiety relief"],
        "seo_keywords": [
            "4-7-8 breathing for sleep guided 1 hour",
            "deep breathing anxiety relief technique",
            "box breathing technique audio guide",
            "breathe to sleep fast guided meditation",
            "panic attack breathing rescue guided",
            "nighttime breathing meditation insomnia",
            "diaphragmatic breathing exercise guided",
            "guided breathing for stress relief 1 hour",
            "slow breathing 6 breaths per minute",
            "calm breathing for racing thoughts",
            "breathing meditation for beginners",
            "wim hof breathing 1 hour guided",
            "breathing exercise for anxiety attack",
            "morning breathing meditation energy",
            "evening breathing meditation deep sleep",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "Quicksand-Bold.ttf",
        "thumbnail_texts": ["Breathe", "4-7-8", "Deep Sleep", "Just Breathe", "Calm"],
        "short_sentences": [
            "Inhale 4. Hold 7. Exhale 8.",
            "Your breath is your power.",
            "Slow down. The world can wait.",
            "Anxiety lies. Breath tells truth.",
            "Right here. Right now. Breathe.",
            "Sleep is medicine.",
            "One breath at a time.",
            "You are safe. You are calm.",
        ],
        "short_quotes": [
            "Breath bridges life and mind. — Thich",
            "Unplug for a few minutes. — Lamott",
            "Stillness is a sanctuary. — Hesse",
            "Rest is not idleness. — Lubbock",
        ],
    },
    "cosmic": {
        "display_name": "Cosmic Chill Sessions",
        "channel_id": "UCz-4TrUlzmf0L3cWedyfPkw",
        "drive_folder_id": "1UD4SoxYXOnCWklbffr32glC5usWfgZvh",
        "clips_folder_id": "1yVrpOA8vU0jnAiL1N5JmLt422tBosBwA",
        "drive_account": "hesap101",
        "youtube_account": "hesap101",
        "concept": "space ambient cosmic lofi",
        "crossfade_seconds": 6,
        "video_keywords": ["space music", "cosmic ambient", "galaxy music", "universe sounds", "ambient space"],
        "seo_keywords": [
            "cosmic ambient music 1 hour",
            "space meditation music deep universe",
            "galaxy lofi chill beats",
            "outer space ambient relaxation",
            "cosmic chill study music",
            "universe sounds meditation",
            "space lofi beats focus",
            "interstellar ambient music sleep",
            "cosmic healing frequency music",
            "deep space ambient soundscape",
            "galaxy meditation music 1 hour",
            "space music for sleep and relaxation",
            "cosmic lofi hip hop beats",
            "nebula ambient chill music",
            "astronaut chill music space vibes",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "SpaceGrotesk-Bold.ttf",
        "thumbnail_texts": ["COSMIC CHILL", "DEEP SPACE", "GALAXY VIBES", "UNIVERSE", "STELLAR"],
        "short_sentences": [
            "You are made of stardust.",
            "The universe is 13.8B years old. Relax.",
            "Stars don't rush. Neither should you.",
            "Float between galaxies.",
            "Cosmic vibes. Terrestrial mind.",
            "The universe doesn't rush.",
            "A star exploded to make you.",
            "Travel light years. Stay seated.",
        ],
        "short_quotes": [
            "We are made of star-stuff. — Sagan",
            "Universe owes you nothing. — Tyson",
            "Are we alone? — Arthur C. Clarke",
        ],
    },
    "ocean": {
        "display_name": "Ocean Depths Meditation",
        "channel_id": "UCDJdUJZX6hLDn51lgt9hXdg",
        "drive_folder_id": "19Srzq7fU4f9GkTran6sJ8H4HH9X_IMFV",
        "clips_folder_id": "1SF5jctOZM8D6QWHp4WHN-wYJQRGT4_ck",
        "drive_account": "hesap101",
        "youtube_account": "hesap101",
        "concept": "ocean depths meditation underwater ambient",
        "crossfade_seconds": 8,
        "video_keywords": ["ocean meditation", "underwater sounds", "whale sounds", "deep sea music", "sleep music"],
        "seo_keywords": [
            "deep ocean meditation music 1 hour",
            "whale sounds sleep meditation",
            "underwater ambient soundscape relaxation",
            "ocean depths sleep music",
            "deep sea meditation sounds",
            "whale song meditation 1 hour",
            "underwater acoustic meditation",
            "ocean waves deep sleep music",
            "marine life ambient sounds",
            "deep ocean healing music",
            "underwater meditation for anxiety",
            "ocean depth sleep soundscape",
            "whale and ocean sounds meditation",
            "deep sea ambient music relaxation",
            "underwater world meditation sleep",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "Marcellus-Regular.ttf",
        "thumbnail_texts": ["Deep Ocean", "Whale Songs", "Ocean Depths", "Underwater", "Sea Calm"],
        "short_sentences": [
            "Whale song: original meditation.",
            "Sink deep. Resurface renewed.",
            "Below the surface, all is still.",
            "The deepest ocean is the quietest.",
            "Ancient waters. Ancient peace.",
            "Dive deep. Come up lighter.",
            "The ocean breathes. Follow it.",
            "Salt heals. Sound heals.",
        ],
        "short_quotes": [
            "The sea casts its spell. — Cousteau",
            "One drop holds all secrets. — Gibran",
            "We are tied to the ocean. — JFK",
        ],
    },
    "mediterranean": {
        "display_name": "Mediterranean Solstice",
        "channel_id": "UCdDfJ3Fwuoput-VbKVzWcFQ",
        "drive_folder_id": "1WaN6yCh114o0Z7WPwYfxFDUMYngBPTOf",
        "clips_folder_id": "1WcIlDzRP04dYKjZ_sIAwmYDrLWXN6Rw_",
        "drive_account": "hesap100",
        "youtube_account": "hesap100",
        "concept": "mediterranean lounge ethnic chill",
        "crossfade_seconds": 5,
        "video_keywords": ["mediterranean music", "ethnic lounge", "greek music", "summer chill", "solstice music"],
        "seo_keywords": [
            "mediterranean lounge music 1 hour",
            "greek island summer chill music",
            "mediterranean ethnic ambient mix",
            "santorini sunset lounge music",
            "mediterranean solstice chill beats",
            "greek taverna lounge ambient",
            "aegean sea chill music",
            "mediterranean summer night music",
            "ethnic lounge chill mix 2026",
            "istanbul rooftop lounge music",
            "mediterranean villa ambient music",
            "greek summer lounge beats",
            "mediterranean ethnic fusion chill",
            "cyprus sunset lounge music",
            "mediterranean coast ambient mix",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "CormorantGaramond-Bold.ttf",
        "thumbnail_texts": ["Mediterranean", "Solstice", "Aegean Chill", "Greek Vibes", "Sunset Lounge"],
        "short_sentences": [
            "Aegean breeze. Olive trees. This track.",
            "Slow down. Mediterranean demands it.",
            "Blue and white. Sun and sound.",
            "Ancient light meets modern rhythm.",
            "The best talks happen after sunset.",
            "Opa. Volume up.",
            "Mediterranean time is the only time.",
            "Your table has a view. Ears have this.",
        ],
        "short_quotes": [
            "Mediterranean: beginning of everything.",
            "Strange towns. Best sensations. — Stark",
            "Travel brings new vigor. — Seneca",
        ],
    },
    "rain": {
        "display_name": "Urban Rain Vibes",
        "channel_id": "UCGXdnwMIJ2HCn3FfUm6NWKw",
        "drive_folder_id": "1JqJKwezAdBJd-7jycvMBvc8GVobwJU1c",
        "clips_folder_id": "17250ljI8QuflenzeJLzi2sp1z5zsBmYu",
        "drive_account": "hesap100",
        "youtube_account": "hesap100",
        "concept": "urban rain chill beats city ambience",
        "crossfade_seconds": 4,
        "video_keywords": ["rain music", "city rain ambience", "urban chill", "rainy day beats", "rain lofi"],
        "seo_keywords": [
            "tokyo rain street ambience music",
            "new york rainy rooftop chill beats",
            "urban rain lofi 1 hour",
            "city rain sounds chill music",
            "rainy day lofi hip hop",
            "london rain cafe ambience music",
            "urban rain meditation relaxation",
            "paris rainy street lofi beats",
            "city rain sounds for sleep",
            "rainy city night chill music",
            "urban rain study music 1 hour",
            "city rain ambience focus music",
            "rainy tokyo lofi beats study",
            "urban rain sounds relaxation",
            "city rain night lofi mix",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "SpaceGrotesk-Bold.ttf",
        "thumbnail_texts": ["URBAN RAIN", "CITY VIBES", "RAINY NIGHT", "TOKYO RAIN", "CHILL RAIN"],
        "short_sentences": [
            "Rain on glass. Music in ears.",
            "Tokyo, 2 AM. You know this.",
            "Every raindrop: tiny percussion.",
            "Urban souls find peace in rain.",
            "Coffee. Window. Rain. Playlist.",
            "Gray skies. Warm sounds.",
            "Headphones in. World out. Rain on.",
            "Some playlists are made for rain.",
        ],
        "short_quotes": [
            "Sound of rain needs no translation. — Watts",
            "Rainy days: tea and a book. — Watterson",
            "Dance in the rain. — Greene",
        ],
    },
}

# Video süresi - minimum 1 saat, doğal bitiş için son şarkı tamamlanır
MIN_VIDEO_DURATION_SECONDS = 3600  # 60 dk minimum

# Geçici dosya klasörü
TEMP_DIR = "/tmp/youtube-bot"

# Kanal bazlı ton/stil ayarları (Gemini için, SEO yapısı kodda zorlanıyor)
CHANNEL_PROMPTS = {
    "coding": {
        "title_style": "Cozy, chill, study-focused tone. Use 1 emoji from: 🎵☕🌧️🌙. Modifier examples: '1 HOUR', 'DEEP FOCUS', '2 AM SESSION', 'NO ADS'.",
        "description_style": "Warm and inviting tone. Mention studying, coding, focus, productivity naturally. 3-4 sentences.",
    },
    "zen": {
        "title_style": "Spiritual, peaceful, descriptive tone. Use 1 emoji from: 🕉️🧘🌸🪷. Modifier examples: '1 HOUR', 'DEEP HEALING', 'INNER PEACE', 'STRESS RELIEF'.",
        "description_style": "Spiritual and grounding tone. Mention yoga, meditation, mindfulness, healing. 4-5 sentences with peaceful tone.",
    },
    "vault": {
        "title_style": "Aggressive, short, hard-hitting. Use 1 emoji from: 🔥💰⚡🐺. Modifier examples: 'GRINDSET', 'NO EXCUSES', 'LOCK IN', '1 HOUR'. ALL CAPS allowed for impact.",
        "description_style": "Short, punchy, motivational. Sigma/grindset language. 2-3 short intense sentences.",
    },
    "chakra": {
        "title_style": "Spiritual, frequency-focused, descriptive. Use 1 emoji from: ✨🔮💫🪷. Modifier examples: '1 HOUR', 'DEEP HEALING', 'MANIFEST', 'CLEANSE'.",
        "description_style": "Mystical and healing tone. Mention specific chakras, frequencies (Hz), benefits. 4-5 sentences.",
    },
    "beach": {
        "title_style": "Fun, summery, party energy. Use 1 emoji from: 🌴☀️🏖️🍹🌊. Modifier examples: '2026', 'SUMMER MIX', 'POOL PARTY', '1 HOUR'.",
        "description_style": "Energetic and bright tone. Mention summer, beach, vacation, party. 3-4 upbeat sentences.",
    },
    "summer": {
        "title_style": "Smooth, sophisticated, lounge feel. Use 1 emoji from: 🌅🍸🌊✨. Modifier examples: 'SUNSET MIX', 'GOLDEN HOUR', 'LUXURY', '1 HOUR'.",
        "description_style": "Refined and chill tone. Mediterranean, lounge, sunset, rooftop language. 3-4 sophisticated sentences.",
    },
    "pets": {
        "title_style": "Warm, caring, problem-solving tone. Use 1 emoji from: 🐾🐶🐱🦮. Modifier examples: '1 HOUR', 'VET APPROVED', 'CALMING', 'PROVEN'.",
        "description_style": "Caring and helpful tone. Mention pet anxiety, separation, calming, vet-recommended. 4-5 warm sentences.",
    },
    "breathe": {
        "title_style": "Calm, sleep-focused, healing tone. Use 1 emoji from: 😴💤🌙🫁. Modifier examples: 'GUIDED', 'DEEP SLEEP', 'ANXIETY RELIEF', '1 HOUR'.",
        "description_style": "Soft and reassuring tone. Mention sleep, anxiety, breathing techniques, relaxation. 4-5 gentle sentences.",
    },
    "cosmic": {
        "title_style": "Dreamy, cosmic, space-focused tone. Use 1 emoji from: 🌌🚀⭐🪐. Modifier examples: '1 HOUR', 'DEEP SPACE', 'COSMIC CHILL', 'GALAXY VIBES'.",
        "description_style": "Mystical and expansive tone. Mention space, galaxies, cosmos, universe, stars. 3-4 sentences.",
    },
    "ocean": {
        "title_style": "Deep, calm, oceanic tone. Use 1 emoji from: 🌊🐋🌙💙. Modifier examples: '1 HOUR', 'DEEP OCEAN', 'WHALE SONGS', 'SLEEP MUSIC'.",
        "description_style": "Peaceful and deep tone. Mention ocean, whales, underwater, sleep, relaxation. 4-5 sentences.",
    },
    "mediterranean": {
        "title_style": "Warm, ethnic, sophisticated tone. Use 1 emoji from: 🌅🫒🌊☀️. Modifier examples: 'SUNSET MIX', 'SOLSTICE', 'GREEK VIBES', '1 HOUR'.",
        "description_style": "Warm and cultural tone. Mention Mediterranean, Greek islands, Aegean, summer, lounge. 3-4 sentences.",
    },
    "rain": {
        "title_style": "Cozy, urban, atmospheric tone. Use 1 emoji from: 🌧️🏙️☔🎵. Modifier examples: '1 HOUR', 'TOKYO RAIN', 'CITY VIBES', 'RAINY NIGHT'.",
        "description_style": "Cozy and atmospheric tone. Mention city rain, urban sounds, relaxation, chill. 3-4 sentences.",
    },
}
