"""
Kanal ayarları - tüm 12 kanalın yapılandırması burada.
"""

CHANNELS = {
    "coding": {
        "display_name": "Music for Coding and Focus",
        "channel_id": "UCkVKKmob42pgVahy7iN8dJg",
        "drive_folder_id": "1ZGDsj91rLyAn53QADHF-XB4nk63_VWYL",
        "clips_folder_id": "1WS1MCEihIQXlhldY2-CYodDpu2ls5hBb",
        "drive_account": "hesap98",
        "youtube_account": "hesap98",
        "concept": "lofi hip hop study music",
        "crossfade_seconds": 4,
        "video_keywords": ["lofi", "study music", "chill beats", "coding music", "focus music"],
        "seo_keywords": [
            "late night coding session music",
            "rainy lofi cafe ambience",
            "lofi for programmers focus",
            "1 hour coding music no ads",
            "midnight study lofi mix",
            "deep work lofi beats",
            "cozy coffee shop lofi",
            "study with me lofi rain",
            "lofi for software engineers",
            "lofi study session 2026",
            "focus music for coding deep work",
            "chill beats for late night work",
            "lofi hip hop study beats playlist",
            "coffee shop ambience study music",
            "night owl coding lofi playlist",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "SpaceGrotesk-Bold.ttf",
        "thumbnail_texts": ["DEEP FOCUS", "CODE MODE", "FOCUS", "STUDY SESSION", "LOCK IN"],
        "short_sentences": [
            "Your best code is written in silence.",
            "Coffee. Lo-fi. Terminal. Repeat.",
            "Deep work begins when world goes quiet.",
            "2 AM and you're in the zone.",
            "Focus is not a talent. It's a habit.",
            "Debug mode: music on, world off.",
            "Ship it. But first, lock in.",
            "One tab open. Zero distractions.",
        ],
        "short_quotes": [
            "First, solve the problem. — John Johnson",
            "Simplicity is efficiency. — Austin Freeman",
            "Focus on what you won't do. — Carmack",
            "The scariest moment is before you start. — King",
        ],
        "long_video_comments": [
            "☕ This mix was made for the 2 AM sessions. Drop a 🎵 if you're coding right now.",
            "💻 Deep focus unlocked. Full playlist on our channel for your next session.",
            "🌧️ Rainy night, hot coffee, lofi beats. The perfect coding setup. Enjoy the mix!",
            "⌨️ Your terminal is open. Your coffee is hot. This mix has you covered for the next hour.",
            "🎵 Built this mix for the nights when deadlines are real and focus is everything.",
            "🌙 Late night coders unite. Drop your language in the comments — what are you building?",
            "☕ No ads. No interruptions. Just 1 hour of pure focus music. You're welcome.",
            "💡 The best ideas happen after midnight with the right music. Stay in the zone.",
            "🖥️ One hour. Full focus. No distractions. Let's get it done.",
            "🎧 Coded with lofi in the background? Same. This one's for you. Drop a ☕ below.",
            "🌙 Your brain enters deep work mode when the beats are right. This is that mix.",
            "💻 Whether you're debugging or shipping features, this mix keeps you locked in.",
            "☕ Cozy. Focused. Unstoppable. That's the energy this mix delivers.",
            "🎵 Comment your current project below — would love to know what you're building!",
            "🌧️ Rain sounds + lofi beats = the ultimate coding atmosphere. Enjoy every minute.",
            "⌨️ No skip button needed. This mix flows seamlessly for 1 full hour of deep work.",
            "💡 Productivity tip: headphones on, notifications off, this mix on repeat.",
            "🌙 2 AM energy in a 1-hour mix. Code hard, rest harder.",
            "☕ This playlist has helped thousands of developers stay focused. Now it's your turn.",
            "🎧 Built different for those who build things. Full focus mix — enjoy.",
        ],
        "short_video_comments": [
            "☕ Full 1-hour mix on our channel. Lock in.",
            "💻 Deep focus mode. Full version ↑",
            "🎵 1 hour. No ads. Just focus. Check our channel.",
            "⌨️ Stay in the zone. Full mix on our channel.",
            "🌙 Late night coding mix. Full version above.",
            "☕ Coffee + lofi = deep work. Full mix on our channel.",
            "💡 Focus unlocked. 1-hour version on our channel.",
            "🎧 No distractions. Full mix on our channel.",
            "🌧️ Rainy lofi vibes. Full hour on our channel.",
            "💻 Built for coders. Full mix above.",
            "☕ Your focus playlist is waiting. Full version ↑",
            "⌨️ Code mode activated. Full mix on our channel.",
            "🎵 1 hour of this. Full version on our channel.",
            "🌙 2 AM energy. Full mix above.",
            "💡 Deep work starts here. Full version ↑",
            "🎧 Headphones on. Full mix on our channel.",
            "☕ Stay focused. Full 1-hour mix above.",
            "💻 Lofi for coders. Full version on our channel.",
            "🌧️ Rain + code + lofi. Full mix ↑",
            "⌨️ Lock in. Full hour on our channel.",
        ],
    },
    "zen": {
        "display_name": "Zen Yoga Music",
        "channel_id": "UCwCgjS5hnrIcnbgDTT6w59Q",
        "drive_folder_id": "1bk6DFdWy0s_WCoIMBN_wfotFeBpTM9_2",
        "clips_folder_id": "12bTsKRMLJxQrF0XpvXL7gBpc8q3QJZ7d",
        "drive_account": "hesap98",
        "youtube_account": "hesap98",
        "concept": "zen meditation tibetan ambient",
        "crossfade_seconds": 8,
        "video_keywords": ["yoga music", "meditation", "zen", "tibetan", "peaceful music"],
        "seo_keywords": [
            "tibetan singing bowls 1 hour deep healing",
            "morning yoga flow gentle music",
            "zen meditation rain forest sounds",
            "yoga nidra deep sleep music",
            "balance meditation music inner peace",
            "shamanic drumming meditation 1 hour",
            "japanese zen garden ambience music",
            "hatha yoga calming background music",
            "mindfulness meditation 1 hour relaxing",
            "forest bathing meditation nature sounds",
            "bedtime yoga relaxation gentle music",
            "stress relief meditation tibetan bowls",
            "deep meditation music for spiritual healing",
            "kundalini yoga awakening music",
            "calming yoga music for beginners",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "CormorantGaramond-Bold.ttf",
        "thumbnail_texts": ["Tibetan Bowls", "Inner Peace", "Zen Yoga", "Deep Calm", "Morning Zen"],
        "short_sentences": [
            "Still the mind. Free the soul.",
            "Breathe in peace. Breathe out tension.",
            "Your mat is your sanctuary.",
            "Peace is not found. It is practiced.",
            "Soften. Surrender. Release.",
            "Return to yourself, again and again.",
            "There is nowhere to go. You are home.",
            "In silence, you are whole.",
        ],
        "short_quotes": [
            "Peace comes from within. — Buddha",
            "You are the sky. — Pema Chödrön",
            "The quieter you become. — Ram Dass",
            "Yoga is the journey to the self.",
        ],
        "long_video_comments": [
            "🧘 Let this music carry you into stillness. Drop a 🙏 if you're practicing right now.",
            "🪷 One hour of pure zen. May your practice be peaceful and your mind be still.",
            "🕉️ Tibetan bowls have been used for healing for thousands of years. Feel the vibration.",
            "🌸 Whether you're on the mat or just need calm — this mix is here for you.",
            "🧘 Close your eyes. Breathe. You are exactly where you need to be.",
            "🪷 Your nervous system deserves this. Full hour of healing music — enjoy.",
            "🌿 Drop a 🧘 below if this helped you find your center today.",
            "🕉️ Morning yoga, evening wind-down, or midday reset — this mix works for all.",
            "🌸 The world is loud. This is your 1-hour sanctuary. Welcome.",
            "🧘 Inhale peace. Exhale tension. Let the music guide you inward.",
            "🪷 Your mat is waiting. Your breath is ready. The music is here.",
            "🌿 Stillness is not emptiness — it is the fullest version of you.",
            "🕉️ Return to yourself, again and again. That is the practice.",
            "🌸 Feel the ancient vibrations of Tibetan bowls wash over you.",
            "🧘 1 hour of yoga music crafted for deep presence and inner peace.",
            "🪷 Drop a 🌸 if you're finding peace in this moment.",
            "🌿 Let go of everything that no longer serves you. This music helps.",
            "🕉️ Healing begins in silence. This mix creates that silence.",
            "🌸 Your yoga practice is sacred. This music honors that.",
            "🧘 One breath at a time. One pose at a time. You've got this.",
        ],
        "short_video_comments": [
            "🧘 Full 1-hour mix on our channel. Find your peace.",
            "🪷 Inner peace is one click away. Full version ↑",
            "🕉️ 1 hour of zen. Full mix on our channel.",
            "🌸 Breathe. Full version on our channel.",
            "🧘 Your sanctuary awaits. Full mix above.",
            "🪷 Still the mind. Full 1-hour version ↑",
            "🌿 Peace found here. Full mix on our channel.",
            "🕉️ Ancient healing sounds. Full version above.",
            "🌸 1 hour of this on our channel. Come find calm.",
            "🧘 Yoga music all day. Full mix on our channel.",
            "🪷 Let go. Full 1-hour mix above.",
            "🌿 Full zen mix on our channel. 🙏",
            "🕉️ Deep healing. Full version ↑",
            "🌸 Your mat is waiting. Full mix on our channel.",
            "🧘 One hour of stillness. Full version above.",
            "🪷 Breathe in. Full mix on our channel.",
            "🌿 Tibetan bowls await. Full version ↑",
            "🕉️ Peace is practiced. Full mix above.",
            "🌸 Soften. Surrender. Full mix on our channel.",
            "🧘 Return to yourself. Full 1-hour version ↑",
        ],
    },
    "vault": {
        "display_name": "Millionaire Vault",
        "channel_id": "UCpMMN35Cp_DBCyoVJY1R3tw",
        "drive_folder_id": "1ysfqX-UsbTOqX8jE9AZJ1HEb0NNWMSOM",
        "clips_folder_id": "1CJWOvaDl4W-RH0sQBPJXvQ2kgi_iBwZT",
        "drive_account": "hesap97",
        "youtube_account": "hesap97",
        "concept": "dark cinematic trap motivational",
        "crossfade_seconds": 3,
        "video_keywords": ["motivation music", "dark trap", "sigma", "grindset", "hustle"],
        "seo_keywords": [
            "dark trap motivation 1 hour",
            "sigma male grindset music",
            "alpha workout dark beats playlist",
            "millionaire mindset hustle music",
            "lock in mode dark phonk",
            "late night gym motivation trap",
            "ceo morning motivation dark beats",
            "drive home dark trap mix",
            "3 am hustler motivation music",
            "no excuses workout music dark",
            "money mindset dark beats",
            "sigma rules motivation playlist",
            "dark phonk gym workout 2026",
            "high value man motivation music",
            "boss energy dark trap mix",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "BebasNeue-Regular.ttf",
        "thumbnail_texts": ["GRINDSET", "LOCK IN", "NO EXCUSES", "MILLIONAIRE"],
        "short_sentences": [
            "While they sleep, you grind.",
            "Discipline is the new rich.",
            "The weak rest. The hungry execute.",
            "No shortcuts. No excuses. No limits.",
            "Lock in. The world owes you nothing.",
            "Pain today. Legacy tomorrow.",
            "Outwork everyone. Every single day.",
            "Most want success. Few pay for it.",
        ],
        "short_quotes": [
            "Discipline equals freedom. — Jocko",
            "Pray for strength. — Bruce Lee",
            "He who has a why. — Nietzsche",
            "Move mountains. Start small. — Confucius",
        ],
        "long_video_comments": [
            "💰 This is the sound of discipline. Full 1-hour mix to keep you locked in. Drop a 🔥 if you're grinding tonight.",
            "⚡ While others sleep, you work. This mix was built for those who refuse to quit.",
            "🐺 The grind doesn't care about your feelings. Neither does this mix. Lock in.",
            "💰 1 hour of dark trap motivation. No ads. No breaks. Just the grind.",
            "🔥 Drop a 💰 below if you're putting in work right now. We see you.",
            "⚡ Pain today. Legacy tomorrow. This mix is for those who understand the difference.",
            "🐺 Most people want success. Few want to pay for it. Which one are you?",
            "💰 CEO energy. Millionaire mindset. This is your soundtrack.",
            "🔥 3 AM and still grinding? This mix was made for you. No excuses.",
            "⚡ The empire you want won't build itself. Lock in and get to work.",
            "🐺 Every sacrifice you make today compounds into your future. Keep going.",
            "💰 Sigma mindset. Dark beats. 1 hour of pure motivation. You're welcome.",
            "🔥 Comment your goal below. We're all building something. What's yours?",
            "⚡ Discipline is the bridge between goals and achievement. Cross it daily.",
            "🐺 They'll understand the sacrifices when they see the results. Stay focused.",
            "💰 This mix hits different when you know exactly what you're working toward.",
            "🔥 No shortcuts. No excuses. No limits. That's the code. Drop a ⚡ if you live by it.",
            "⚡ Lock in mode activated. Full hour of dark motivation — enjoy the grind.",
            "🐺 The hustle is silent. The results are loud. Keep working.",
            "💰 Built for the ones who outwork everyone else. Every. Single. Day.",
        ],
        "short_video_comments": [
            "🔥 Full 1-hour version on our channel. Lock in.",
            "💰 This is the sound of discipline. Full mix ↑",
            "⚡ No excuses. Full 1-hour mix on our channel.",
            "🐺 Grind mode. Full version above.",
            "🔥 Stay focused. Full mix on our channel.",
            "💰 Millionaire mindset. Full 1-hour mix ↑",
            "⚡ Lock in. Full version on our channel.",
            "🐺 Pain today. Legacy tomorrow. Full mix above.",
            "🔥 1 hour of this on our channel. No ads.",
            "💰 The grind continues. Full mix on our channel.",
            "⚡ Discipline = freedom. Full version ↑",
            "🐺 Outwork everyone. Full mix on our channel.",
            "🔥 CEO energy. Full 1-hour version above.",
            "💰 Dark trap motivation. Full mix on our channel.",
            "⚡ While they sleep. Full version ↑",
            "🐺 No limits. Full mix on our channel.",
            "🔥 Sigma mindset. Full 1-hour mix above.",
            "💰 Built different. Full version on our channel.",
            "⚡ 3 AM grind. Full mix ↑",
            "🐺 Execute. Full 1-hour version on our channel.",
        ],
    },
    "chakra": {
        "display_name": "Chakra Healing Meditation",
        "channel_id": "UCVnJG9DB4jYpv4PMSJvkuIA",
        "drive_folder_id": "1P7O2FBPApSXNjn3JjWzi_GlFDdAoDhYq",
        "clips_folder_id": "1y22dntgRRAtzwt5TP0Ag-w9knmlrmL2n",
        "drive_account": "hesap97",
        "youtube_account": "hesap97",
        "concept": "chakra healing solfeggio frequency",
        "crossfade_seconds": 10,
        "video_keywords": ["chakra healing", "432hz", "528hz", "meditation music", "sound healing"],
        "seo_keywords": [
            "528 Hz love frequency heart chakra",
            "432 Hz deep healing meditation music",
            "741 Hz throat chakra cleanse meditation",
            "396 Hz root chakra grounding music",
            "639 Hz heart chakra love attraction",
            "852 Hz third eye awakening meditation",
            "963 Hz crown chakra divine connection",
            "417 Hz solar plexus power chakra",
            "all 7 chakras balance meditation 1 hour",
            "chakra clearing negative energy removal",
            "solfeggio frequency anxiety relief",
            "chakra healing music sleep meditation",
            "chakra alignment morning meditation",
            "balancing chakras for beginners guided",
            "deep chakra cleansing solfeggio frequencies",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "Marcellus-Regular.ttf",
        "thumbnail_texts": ["Chakra Healing", "528 Hz", "432 Hz", "Frequency Healing", "Sacred Sounds"],
        "short_sentences": [
            "528 Hz — frequency of love.",
            "Your energy centers align now.",
            "Sound is the oldest medicine.",
            "Vibrate higher. Always.",
            "Balance begins from inside.",
            "Ancient frequencies. Modern healing.",
            "Release what blocks you.",
            "You are energy. You are light.",
        ],
        "short_quotes": [
            "Energy, frequency, vibration. — Tesla",
            "The wound is where light enters. — Rumi",
            "Energy flows where attention goes.",
            "Healing others heals yourself.",
        ],
        "long_video_comments": [
            "✨ Let the 528 Hz frequency dissolve what no longer serves you. Drop a 🙏 if you feel it.",
            "🔮 Sound is the oldest medicine. This mix carries ancient healing in every frequency.",
            "💫 Your chakras are aligning as you listen. Trust the process. Trust the vibration.",
            "✨ 1 hour of solfeggio frequencies crafted for deep healing and energetic balance.",
            "🔮 Drop a ✨ if you felt a shift while listening. The frequencies are working.",
            "💫 528 Hz — the frequency of love and DNA repair. Let it work through you.",
            "✨ Every cell in your body is vibrating. This music attunes them to healing.",
            "🔮 Ancient frequencies. Modern healing. Your body knows what it needs.",
            "💫 Energy flows where attention goes. Focus on healing and let this music guide you.",
            "✨ Release what blocks you. Receive what heals you. That's the work.",
            "🔮 Your crown opens. Your roots deepen. Balance is being restored.",
            "💫 Comment which chakra you're working on — root, heart, third eye, or crown.",
            "✨ The 432 Hz frequency resonates with the natural vibration of the universe.",
            "🔮 Negative energy has no place here. This mix cleanses and restores.",
            "💫 Healing is not linear. Trust the vibration. Trust the process.",
            "✨ Drop a 🔮 if you're doing chakra work today. You're not alone.",
            "💫 Sacred sounds for sacred healing. 1 hour of pure frequency medicine.",
            "🔮 Your energy body is real. This music speaks directly to it.",
            "✨ Vibrate higher. Always. This mix helps you do exactly that.",
            "💫 Ancient wisdom encoded in sound. Modern healing through frequency.",
        ],
        "short_video_comments": [
            "✨ Full 1-hour healing mix on our channel. Vibrate higher.",
            "🔮 528 Hz full version ↑ on our channel.",
            "💫 Chakra healing. Full mix on our channel.",
            "✨ Ancient frequencies. Full 1-hour version above.",
            "🔮 Energy flows. Full mix on our channel.",
            "💫 Full healing session ↑ on our channel.",
            "✨ Release and receive. Full version on our channel.",
            "🔮 1 hour of this. Full mix above.",
            "💫 Your chakras are ready. Full mix on our channel.",
            "✨ Align. Full 1-hour version ↑",
            "🔮 Sound heals. Full mix on our channel.",
            "💫 432 Hz full session above.",
            "✨ Vibrate higher. Full mix on our channel.",
            "🔮 Full frequency healing ↑",
            "💫 Balance restored. Full mix on our channel.",
            "✨ Ancient medicine. Full 1-hour version above.",
            "🔮 Cleanse and align. Full mix on our channel.",
            "💫 Sacred sounds. Full version ↑",
            "✨ Healing begins. Full mix on our channel.",
            "🔮 Full chakra session above.",
        ],
    },
    "beach": {
        "display_name": "Beach Club Beats",
        "channel_id": "UC9AcTTuosbZ17P0F0tfMg3g",
        "drive_folder_id": "1S0f5ojyNWHSb8K7RGkwBrcn1vxn1Jnco",
        "clips_folder_id": "1c11dVr0S_cEK5hlxIIQlf_fzor03Mq0O",
        "drive_account": "hesap99",
        "youtube_account": "hesap99",
        "concept": "tropical house beach club",
        "crossfade_seconds": 4,
        "video_keywords": ["beach music", "tropical house", "summer vibes", "ibiza", "deep house"],
        "seo_keywords": [
            "ibiza pool party house mix 2026",
            "tropical house summer beach club",
            "miami beach deep house mix",
            "boat party house music summer",
            "vacation vibes tropical mix 2026",
            "poolside house beats afternoon",
            "sunset beach club mix tropical",
            "tropical deep house lounge",
            "caribbean beach house mix",
            "tulum beach club beats sunset",
            "summer beach house party 2026",
            "tropical poolside chill house mix",
            "beach club afternoon house mix",
            "balearic beach house ibiza vibes",
            "tropical house workout summer mix",
        ],
        "thumbnail_style": "clean",
        "thumbnail_font": "",
        "thumbnail_texts": [],
        "short_sentences": [
            "The ocean called. You answered.",
            "Salt air. Bare feet. Good music.",
            "Every wave is an invitation.",
            "Blue water. Warmer music.",
            "No plans. Just music and ocean.",
            "Life is short. The playlist is long.",
            "Sand in toes. Bass in soul.",
            "Summer doesn't end here.",
        ],
        "short_quotes": [
            "Live in the sunshine. — Emerson",
            "The sea casts its spell. — Cousteau",
            "I am only a child on the beach. — Newton",
        ],
        "long_video_comments": [
            "🌴 Close your eyes. You're at the beach club now. Drop a 🌊 if you feel the vibe.",
            "☀️ Vitamin Sea + tropical house = the only prescription you need right now.",
            "🏖️ Built this mix for the poolside sessions, sunset drives, and summer memories.",
            "🌴 1 hour of pure tropical house. No ads. Just good vibes and good music.",
            "🌊 Drop a 🏖️ if this mix teleported you somewhere warm and beautiful.",
            "☀️ Summer doesn't need a calendar. Just press play and you're there.",
            "🏖️ Salt air. Bare feet. This mix. That's the formula for a perfect summer day.",
            "🌴 From Ibiza to Tulum — this mix captures that beach club energy perfectly.",
            "🌊 Comment where your dream beach destination is below. Mine's in the mix.",
            "☀️ The DJ just dropped. The crowd just moved. You're right there with them.",
            "🏖️ Good vibes travel at the speed of tropical house. Welcome to the party.",
            "🌴 No passport needed. Just headphones and this 1-hour beach club mix.",
            "🌊 Sand between your toes. Bass in your soul. That's what this mix delivers.",
            "☀️ Every wave is an invitation. This music accepts that invitation fully.",
            "🏖️ Drop a ☀️ if this mix made your day a little brighter and warmer.",
            "🌴 Summer 2026 has a soundtrack. You're listening to it right now.",
            "🌊 The ocean called. You answered. Now let this mix take you the rest of the way.",
            "☀️ Life is short. The playlist is long. Make the most of both.",
            "🏖️ Tropical house for the dreamers, the travelers, and the beach lovers.",
            "🌴 This is what summer sounds like. Hope it finds you somewhere warm.",
        ],
        "short_video_comments": [
            "🌴 Full 1-hour beach mix on our channel. Feel the summer.",
            "🌊 Summer vibes. Full version ↑",
            "☀️ Tropical house. Full mix on our channel.",
            "🏖️ Beach club energy. Full 1-hour version above.",
            "🌴 Good vibes. Full mix on our channel.",
            "🌊 Full summer mix ↑ on our channel.",
            "☀️ Ibiza energy. Full version on our channel.",
            "🏖️ 1 hour of this. Full mix above.",
            "🌴 Poolside beats. Full mix on our channel.",
            "🌊 Salt air. Full 1-hour version ↑",
            "☀️ Beach club all day. Full mix on our channel.",
            "🏖️ Full tropical mix above.",
            "🌴 Ocean calling. Full mix on our channel.",
            "🌊 Summer 2026. Full version ↑",
            "☀️ No plans. Full mix on our channel.",
            "🏖️ Bass in soul. Full 1-hour version above.",
            "🌴 Tulum vibes. Full mix on our channel.",
            "🌊 Full beach session ↑",
            "☀️ Vacation mode. Full mix on our channel.",
            "🏖️ Full summer mix above.",
        ],
    },
    "summer": {
        "display_name": "Summer House Music",
        "channel_id": "UC1w2S1apy3UK-pRaIEJBavA",
        "drive_folder_id": "15jR06ZQXUbUb3uk08BHEhwfsLrpr2yEh",
        "clips_folder_id": "1LiywuL07wnWcXM-C0vIwixnV5ztFfBsz",
        "drive_account": "hesap99",
        "youtube_account": "hesap99",
        "concept": "deep house summer mediterranean",
        "crossfade_seconds": 4,
        "video_keywords": ["deep house", "summer house", "mediterranean", "lounge", "chillout"],
        "seo_keywords": [
            "rooftop sunset deep house mix",
            "mediterranean lounge deep house",
            "santorini sunset house music",
            "italian villa chillout vibes",
            "yacht deep house sunset mix",
            "mykonos lounge beats sunset",
            "amalfi coast deep house chill",
            "golden hour rooftop deep house mix",
            "ibiza sunset deep house lounge",
            "luxury hotel lobby chillout mix",
            "monaco sunset deep house lounge",
            "saint tropez deep house mix",
            "cote dazur summer house mix",
            "elegant deep house dinner party",
            "mediterranean villa chillout 2026",
        ],
        "thumbnail_style": "clean",
        "thumbnail_font": "",
        "thumbnail_texts": [],
        "short_sentences": [
            "The golden hour needs a golden track.",
            "Luxury is not a place. It's a feeling.",
            "Wine. View. Music. In that order.",
            "Rooftop. Skyline. Volume up.",
            "Slow down. This is the good part.",
            "Time moves differently here.",
            "Summer light. Summer soul.",
            "Mediterranean air hits different.",
        ],
        "short_quotes": [
            "To travel is to live. — Andersen",
            "Fill life with experiences.",
            "The world is a book. — Augustine",
        ],
        "long_video_comments": [
            "🌅 The golden hour has its own soundtrack. You're listening to it. Drop a 🍸 if you agree.",
            "🌊 Santorini sunset. Deep house. No words needed. Just close your eyes and feel it.",
            "✨ Luxury is not a place — it's a feeling. This mix delivers that feeling for 1 full hour.",
            "🌅 Wine. View. Music. In that order. This mix handles the last part beautifully.",
            "🍸 Drop a 🌅 if this mix transported you to a Mediterranean rooftop tonight.",
            "🌊 Built for the golden hour. The moment when the sun dips low and the music rises.",
            "✨ Rooftop. Skyline. Deep house. The holy trinity of a perfect summer evening.",
            "🌅 Time moves differently on the Mediterranean. This mix captures that perfectly.",
            "🍸 Comment your dream destination below — Santorini, Mykonos, Amalfi, Monaco?",
            "🌊 This mix was made for the moments you'll remember long after summer ends.",
            "✨ The best tables always have a view and the right playlist. This is that playlist.",
            "🌅 Slow down. This is the good part. Let this mix remind you to savor the moment.",
            "🍸 Mediterranean air hits different after dark. So does this deep house mix.",
            "🌊 Drop a ✨ if you're sipping something good and listening to this right now.",
            "✨ Let the deep house carry you to the Côte d'Azur. No passport required.",
            "🌅 1 hour of sophisticated deep house for those who appreciate the finer things.",
            "🍸 Summer light. Summer sound. Summer soul. That's what this mix is about.",
            "🌊 Golden hour energy in every beat. This mix was built for beautiful evenings.",
            "✨ From Monaco to Saint-Tropez — this is the sound of Mediterranean luxury.",
            "🌅 Elegant. Refined. Unforgettable. Just like your best summer memories.",
        ],
        "short_video_comments": [
            "🌅 Full 1-hour mix on our channel. Golden hour vibes.",
            "🌊 Mediterranean deep house. Full version ↑",
            "✨ Luxury feels. Full mix on our channel.",
            "🍸 Rooftop energy. Full 1-hour version above.",
            "🌅 Sunset mix. Full version on our channel.",
            "🌊 Full golden hour mix ↑",
            "✨ Santorini vibes. Full mix on our channel.",
            "🍸 1 hour of this. Full version above.",
            "🌅 Deep house elegance. Full mix on our channel.",
            "🌊 Wine and music. Full 1-hour version ↑",
            "✨ Mediterranean soul. Full mix on our channel.",
            "🍸 Full sunset session above.",
            "🌅 Slow down. Full mix on our channel.",
            "🌊 Monaco energy. Full version ↑",
            "✨ Summer light. Full mix on our channel.",
            "🍸 Full luxury mix above.",
            "🌅 Côte d'Azur vibes. Full mix on our channel.",
            "🌊 Full deep house session ↑",
            "✨ Golden vibes. Full mix on our channel.",
            "🍸 Full Mediterranean mix above.",
        ],
    },
    "pets": {
        "display_name": "Relaxing Dogs and Cats",
        "channel_id": "UCyYCN2hqzJBSA9XNes1Shig",
        "drive_folder_id": "1eY8y0RDewp0lA5fjLuDuvZErOxUnUIW-",
        "clips_folder_id": "1r5YJxeY2s81BZJ-dAqbe8Y-0hgCFh_jf",
        "drive_account": "hesap87",
        "youtube_account": "hesap87",
        "concept": "soft acoustic for pets calm",
        "crossfade_seconds": 6,
        "video_keywords": ["dog music", "cat music", "pet relaxation", "calm pets", "anxiety music"],
        "seo_keywords": [
            "music for dogs home alone anxiety",
            "calming music for stressed cats",
            "puppy sleep music for first night",
            "music for anxious dogs separation",
            "vet recommended dog calming music",
            "music to calm aggressive dogs barking",
            "music for cats during car ride",
            "calm music for new kittens",
            "music for dogs with thunderstorm phobia",
            "music for new puppy first night home",
            "stress relief music for cats anxiety",
            "music for senior dogs sleep peaceful",
            "calm music for rescue dogs adoption",
            "music for dogs while owner away",
            "soothing music for anxious cats vet",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "Nunito-ExtraBold.ttf",
        "thumbnail_texts": ["Calm Pets", "Dog Relax", "Cat Sleep", "Home Alone", "Anxious Pets"],
        "short_sentences": [
            "You're not alone, buddy.",
            "Calm vibes for your best friend.",
            "They can hear the love.",
            "Soft music. Safe space.",
            "For the ones who wait by the door.",
            "Home alone? Not anymore.",
            "They give everything. Give them this.",
            "Safe sounds for sensitive souls.",
        ],
        "short_quotes": [
            "Animals ask no questions. — Eliot",
            "Love an animal, wake your soul.",
            "Treat animals well. — Gandhi",
        ],
        "long_video_comments": [
            "🐾 Drop a 🐶 or 🐱 below if your pet is listening to this right now. We love hearing that!",
            "🦮 This mix was crafted with love for every anxious pup and stressed-out kitty.",
            "🐾 They can't tell you they're anxious. But this music speaks their language.",
            "🐶 Home alone doesn't have to feel scary. This 1-hour mix keeps them company.",
            "🐱 Drop a 🐾 if your pet falls asleep to music. You're doing something beautiful.",
            "🦮 Separation anxiety is real for our pets. This music helps more than you know.",
            "🐾 For the ones who wait by the door — this music tells them they're not forgotten.",
            "🐶 Vet-recommended frequencies wrapped in gentle acoustic music. Pure love.",
            "🐱 Your cat is napping. Your dog is dreaming. All is well. That's what this does.",
            "🦮 Comment your pet's name below. We want to dedicate this mix to them. 🐾",
            "🐾 They give us everything. The least we can do is give them calm, safe music.",
            "🐶 Thunderstorm outside? This mix is specifically designed to help with that anxiety.",
            "🐱 New kitten? Rescue dog? This music helps them settle into their new home faster.",
            "🦮 Safe sounds for sensitive souls. That's what every pet deserves.",
            "🐾 Drop a ❤️ if your pet makes your life infinitely better. They deserve this mix.",
            "🐶 Music therapy for pets is proven and real. This mix is your starting point.",
            "🐱 Soft music. Safe space. That's the promise of every video on this channel.",
            "🦮 For the senior dogs who sleep a little more these days — this one's for you.",
            "🐾 They waited all day for you. While they wait, this music keeps them calm.",
            "🐶 Every tail wag and purr is a five-star review. Thanks for sharing this with them.",
        ],
        "short_video_comments": [
            "🐾 Full 1-hour mix on our channel. Calm pets.",
            "🐶 Safe sounds. Full version ↑",
            "🐱 Calming music. Full mix on our channel.",
            "🦮 For anxious pets. Full 1-hour version above.",
            "🐾 They deserve this. Full mix on our channel.",
            "🐶 Full pet mix ↑ on our channel.",
            "🐱 Home alone help. Full version on our channel.",
            "🦮 1 hour of this. Full mix above.",
            "🐾 Soft music. Full mix on our channel.",
            "🐶 Dog anxiety help. Full 1-hour version ↑",
            "🐱 Cat sleep music. Full mix on our channel.",
            "🦮 Full calming session above.",
            "🐾 Safe space sounds. Full mix on our channel.",
            "🐶 Separation anxiety. Full version ↑",
            "🐱 New pet help. Full mix on our channel.",
            "🦮 Full pet therapy mix above.",
            "🐾 Waiting by the door. Full mix on our channel.",
            "🐶 Full dog music ↑",
            "🐱 Purr approved. Full mix on our channel.",
            "🦮 Full calming mix above.",
        ],
    },
    "breathe": {
        "display_name": "Breathe and Chill",
        "channel_id": "UCqBZrQuzsfp8_sTRu97T3VA",
        "drive_folder_id": "1ivZr7goxS7VJpMwyLqwCkP1hcezievW-",
        "clips_folder_id": "17pRNXvwn2NXYHf9zX-g6fxRrwpSesO_N",
        "drive_account": "hesap87",
        "youtube_account": "hesap87",
        "concept": "breathing meditation 4-7-8",
        "crossfade_seconds": 8,
        "video_keywords": ["breathing exercise", "4-7-8 breathing", "meditation", "calm music", "anxiety relief"],
        "seo_keywords": [
            "4-7-8 breathing for sleep guided 1 hour",
            "deep breathing anxiety relief technique",
            "box breathing technique audio guide",
            "breathe to sleep fast guided meditation",
            "panic attack breathing rescue guided",
            "nighttime breathing meditation insomnia",
            "diaphragmatic breathing exercise guided",
            "guided breathing for stress relief 1 hour",
            "slow breathing 6 breaths per minute",
            "calm breathing for racing thoughts",
            "breathing meditation for beginners",
            "wim hof breathing 1 hour guided",
            "breathing exercise for anxiety attack",
            "morning breathing meditation energy",
            "evening breathing meditation deep sleep",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "Quicksand-Bold.ttf",
        "thumbnail_texts": ["Breathe", "4-7-8", "Deep Sleep", "Just Breathe", "Calm"],
        "short_sentences": [
            "Inhale 4. Hold 7. Exhale 8.",
            "Your breath is your power.",
            "Slow down. The world can wait.",
            "Anxiety lies. Breath tells truth.",
            "Right here. Right now. Breathe.",
            "Sleep is medicine.",
            "One breath at a time.",
            "You are safe. You are calm.",
        ],
        "short_quotes": [
            "Breath bridges life and mind. — Thich",
            "Unplug for a few minutes. — Lamott",
            "Stillness is a sanctuary. — Hesse",
            "Rest is not idleness. — Lubbock",
        ],
        "long_video_comments": [
            "🌙 Inhale for 4. Hold for 7. Exhale for 8. Drop a 💤 if this helped you sleep tonight.",
            "😴 Your nervous system deserves this. 1 hour of guided breathing and calm music.",
            "🫁 Anxiety lies. Your breath always tells the truth. Come back to it.",
            "🌙 The 4-7-8 technique is one of the most powerful tools for sleep. Use it tonight.",
            "💤 Drop a 🌙 if you're listening to this right now and feeling calmer already.",
            "😴 You don't need to fix everything tonight. Just breathe. That's enough.",
            "🫁 Your breath is the most powerful tool you own. This mix helps you use it.",
            "🌙 Panic attack? Racing thoughts? Slow your breath with this. It works.",
            "💤 Sleep is not a luxury — it's medicine. This mix is your prescription.",
            "😴 One breath at a time is all it takes. You've got this. We've got the music.",
            "🫁 Comment below if you found this helpful for anxiety or sleep. We read every one.",
            "🌙 The nervous system heals in stillness. Give it this hour. You deserve it.",
            "💤 Nothing is urgent enough to stop breathing well. Slow down with this mix.",
            "😴 Tonight, rest is enough. You are enough. Let this music hold you.",
            "🫁 Drop a 💙 if you needed this today. No explanation needed. We understand.",
            "🌙 Right here. Right now. Just breathe. Everything else can wait.",
            "💤 Guided breathing + calming music = the best sleep protocol you'll ever find.",
            "😴 Your body knows how to heal. This music helps it remember.",
            "🫁 Slow breath in. Slow breath out. You are safe. You are calm. You are okay.",
            "🌙 Built for the restless nights and the anxious minds. This one's for you.",
        ],
        "short_video_comments": [
            "🌙 Full 1-hour mix on our channel. Just breathe.",
            "😴 Sleep better. Full version ↑",
            "🫁 Anxiety relief. Full mix on our channel.",
            "💤 4-7-8 breathing. Full 1-hour version above.",
            "🌙 You are safe. Full mix on our channel.",
            "😴 Full sleep mix ↑ on our channel.",
            "🫁 Slow down. Full version on our channel.",
            "💤 1 hour of calm. Full mix above.",
            "🌙 Breathe. Full mix on our channel.",
            "😴 Deep sleep help. Full 1-hour version ↑",
            "🫁 Panic relief. Full mix on our channel.",
            "💤 Full breathing session above.",
            "🌙 Rest is medicine. Full mix on our channel.",
            "😴 Racing thoughts? Full version ↑",
            "🫁 Tonight, breathe. Full mix on our channel.",
            "💤 Full calm session above.",
            "🌙 One breath. Full mix on our channel.",
            "😴 Full sleep guide ↑",
            "🫁 You got this. Full mix on our channel.",
            "💤 Full breathing mix above.",
        ],
    },
    "cosmic": {
        "display_name": "Cosmic Chill Sessions",
        "channel_id": "UCz-4TrUlzmf0L3cWedyfPkw",
        "drive_folder_id": "1UD4SoxYXOnCWklbffr32glC5usWfgZvh",
        "clips_folder_id": "1yVrpOA8vU0jnAiL1N5JmLt422tBosBwA",
        "drive_account": "hesap101",
        "youtube_account": "hesap101",
        "concept": "space ambient cosmic lofi",
        "crossfade_seconds": 6,
        "video_keywords": ["space music", "cosmic ambient", "galaxy music", "universe sounds", "ambient space"],
        "seo_keywords": [
            "cosmic ambient music 1 hour",
            "space meditation music deep universe",
            "galaxy lofi chill beats",
            "outer space ambient relaxation",
            "cosmic chill study music",
            "universe sounds meditation",
            "space lofi beats focus",
            "interstellar ambient music sleep",
            "cosmic healing frequency music",
            "deep space ambient soundscape",
            "galaxy meditation music 1 hour",
            "space music for sleep and relaxation",
            "cosmic lofi hip hop beats",
            "nebula ambient chill music",
            "astronaut chill music space vibes",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "SpaceGrotesk-Bold.ttf",
        "thumbnail_texts": ["COSMIC CHILL", "DEEP SPACE", "GALAXY VIBES", "UNIVERSE", "STELLAR"],
        "short_sentences": [
            "You are made of stardust.",
            "The universe is 13.8B years old. Relax.",
            "Stars don't rush. Neither should you.",
            "Float between galaxies.",
            "Cosmic vibes. Terrestrial mind.",
            "The universe doesn't rush.",
            "A star exploded to make you.",
            "Travel light years. Stay seated.",
        ],
        "short_quotes": [
            "We are made of star-stuff. — Sagan",
            "Universe owes you nothing. — Tyson",
            "Are we alone? — Arthur C. Clarke",
        ],
        "long_video_comments": [
            "🌌 You are made of stardust. Drop a ⭐ if that thought makes you feel something.",
            "🚀 The universe is 13.8 billion years old. Your deadline is not that important. Relax.",
            "🪐 Close your eyes. You are no longer on Earth. This mix takes you the rest of the way.",
            "🌌 Stars don't rush their light to reach you. Neither should you rush through life.",
            "⭐ Drop a 🌌 if this music made the universe feel a little less lonely tonight.",
            "🚀 Somewhere in the cosmos, a frequency found you. That's not an accident.",
            "🪐 We are all just advanced stardust floating on a rock. This music honors that.",
            "🌌 Cosmic vibes for terrestrial minds. 1 hour to float between galaxies without leaving.",
            "⭐ The Milky Way has no algorithm. Neither does this mix. Just pure space energy.",
            "🚀 Comment: if you could travel to any galaxy, where would you go? Drop it below.",
            "🪐 A star exploded billions of years ago so that you could exist. Think about that.",
            "🌌 Gravity pulls you down. Music lifts you up. This mix does both simultaneously.",
            "⭐ Travel light years without leaving your chair. That's the power of cosmic music.",
            "🚀 The universe doesn't rush. Take a lesson from it with this 1-hour ambient mix.",
            "🪐 Drop a 🚀 if you're listening to this and feeling genuinely at peace right now.",
            "🌌 Deep space. Deep focus. Deep relaxation. That's the cosmic chill experience.",
            "⭐ We are not alone in this universe. And we're not alone in this moment either.",
            "🚀 Nebula colors. Galaxy sounds. 1 hour of the most beautiful music in the cosmos.",
            "🪐 Your problems are small compared to the universe. This music reminds you of that.",
            "🌌 Float. Drift. Explore. That's the only agenda this mix has for you.",
        ],
        "short_video_comments": [
            "🌌 Full 1-hour cosmic mix on our channel. Float.",
            "🚀 Space vibes. Full version ↑",
            "⭐ Stardust energy. Full mix on our channel.",
            "🪐 Galaxy chill. Full 1-hour version above.",
            "🌌 You are cosmic. Full mix on our channel.",
            "🚀 Full space mix ↑ on our channel.",
            "⭐ Stars don't rush. Full version on our channel.",
            "🪐 1 hour of cosmos. Full mix above.",
            "🌌 Deep space. Full mix on our channel.",
            "🚀 Universe energy. Full 1-hour version ↑",
            "⭐ Cosmic focus. Full mix on our channel.",
            "🪐 Full galaxy session above.",
            "🌌 Float away. Full mix on our channel.",
            "🚀 Nebula vibes. Full version ↑",
            "⭐ Made of stardust. Full mix on our channel.",
            "🪐 Full cosmic session above.",
            "🌌 Interstellar chill. Full mix on our channel.",
            "🚀 Full space ambient ↑",
            "⭐ Relax. Universe says so. Full mix on our channel.",
            "🪐 Full cosmic mix above.",
        ],
    },
    "ocean": {
        "display_name": "Ocean Depths Meditation",
        "channel_id": "UCDJdUJZX6hLDn51lgt9hXdg",
        "drive_folder_id": "19Srzq7fU4f9GkTran6sJ8H4HH9X_IMFV",
        "clips_folder_id": "1SF5jctOZM8D6QWHp4WHN-wYJQRGT4_ck",
        "drive_account": "hesap101",
        "youtube_account": "hesap101",
        "concept": "ocean depths meditation underwater ambient",
        "crossfade_seconds": 8,
        "video_keywords": ["ocean meditation", "underwater sounds", "whale sounds", "deep sea music", "sleep music"],
        "seo_keywords": [
            "deep ocean meditation music 1 hour",
            "whale sounds sleep meditation",
            "underwater ambient soundscape relaxation",
            "ocean depths sleep music",
            "deep sea meditation sounds",
            "whale song meditation 1 hour",
            "underwater acoustic meditation",
            "ocean waves deep sleep music",
            "marine life ambient sounds",
            "deep ocean healing music",
            "underwater meditation for anxiety",
            "ocean depth sleep soundscape",
            "whale and ocean sounds meditation",
            "deep sea ambient music relaxation",
            "underwater world meditation sleep",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "Marcellus-Regular.ttf",
        "thumbnail_texts": ["Deep Ocean", "Whale Songs", "Ocean Depths", "Underwater", "Sea Calm"],
        "short_sentences": [
            "Whale song: original meditation.",
            "Sink deep. Resurface renewed.",
            "Below the surface, all is still.",
            "The deepest ocean is the quietest.",
            "Ancient waters. Ancient peace.",
            "Dive deep. Come up lighter.",
            "The ocean breathes. Follow it.",
            "Salt heals. Sound heals.",
        ],
        "short_quotes": [
            "The sea casts its spell. — Cousteau",
            "One drop holds all secrets. — Gibran",
            "We are tied to the ocean. — JFK",
        ],
        "long_video_comments": [
            "🌊 Sink into the deep. Resurface renewed. Drop a 🐋 if you felt that transformation.",
            "💙 Whale song is the original meditation. Ancient. Powerful. Healing. Feel it.",
            "🌊 Below the surface, everything is still. This music takes you exactly there.",
            "💙 The deepest ocean is also the quietest. Let this mix bring you to that depth.",
            "🐋 Drop a 🌊 if the whale songs in this mix gave you chills in the best possible way.",
            "🌊 Ancient waters carry ancient peace. This 1-hour mix lets you access both.",
            "💙 We are tied to the ocean. Our bodies are mostly water. This music reminds us.",
            "🌊 Dive deep. Come up lighter. That's the promise of ocean meditation music.",
            "🐋 Comment what ocean you'd most want to explore — Pacific, Atlantic, or Arctic?",
            "🌊 The tide goes out. The tide comes back. So do you. This music holds that truth.",
            "💙 Salt heals. Sound heals. This mix gives you both in one beautiful hour.",
            "🌊 The ocean breathes. Follow its rhythm. Let this music be your guide.",
            "🐋 Drop a 💙 if ocean sounds are your go-to for sleep, meditation, or stress relief.",
            "🌊 Marine life has been making music for millions of years. We just pressed record.",
            "💙 Let the whale's call reset your nervous system. It's ancient technology.",
            "🌊 The sea knows your name. This music helps you hear it calling.",
            "🐋 Underwater, there is no noise from the surface. That's the peace this mix creates.",
            "🌊 1 hour of deep ocean meditation. For the sleep deprived, the anxious, and the tired.",
            "💙 Dive into the most calming soundscape on the internet. You found the right place.",
            "🌊 From the deepest trenches to the gentlest waves — this mix has it all.",
        ],
        "short_video_comments": [
            "🌊 Full 1-hour ocean mix on our channel. Dive deep.",
            "🐋 Whale songs. Full version ↑",
            "💙 Ocean meditation. Full mix on our channel.",
            "🌊 Ancient peace. Full 1-hour version above.",
            "🐋 Sink deep. Full mix on our channel.",
            "🌊 Full ocean mix ↑ on our channel.",
            "💙 Underwater calm. Full version on our channel.",
            "🐋 1 hour of ocean. Full mix above.",
            "🌊 Deep sea sounds. Full mix on our channel.",
            "💙 Salt heals. Full 1-hour version ↑",
            "🐋 Ocean breathes. Full mix on our channel.",
            "🌊 Full whale song session above.",
            "💙 Resurface renewed. Full mix on our channel.",
            "🐋 Ancient waters. Full version ↑",
            "🌊 Sleep music. Full mix on our channel.",
            "💙 Full deep ocean session above.",
            "🐋 Marine meditation. Full mix on our channel.",
            "🌊 Full ocean depths ↑",
            "💙 Tide and peace. Full mix on our channel.",
            "🐋 Full ocean mix above.",
        ],
    },
    "mediterranean": {
        "display_name": "Mediterranean Solstice",
        "channel_id": "UCdDfJ3Fwuoput-VbKVzWcFQ",
        "drive_folder_id": "1WaN6yCh114o0Z7WPwYfxFDUMYngBPTOf",
        "clips_folder_id": "1WcIlDzRP04dYKjZ_sIAwmYDrLWXN6Rw_",
        "drive_account": "hesap100",
        "youtube_account": "hesap100",
        "concept": "mediterranean lounge ethnic chill",
        "crossfade_seconds": 5,
        "video_keywords": ["mediterranean music", "ethnic lounge", "greek music", "summer chill", "solstice music"],
        "seo_keywords": [
            "mediterranean lounge music 1 hour",
            "greek island summer chill music",
            "mediterranean ethnic ambient mix",
            "santorini sunset lounge music",
            "mediterranean solstice chill beats",
            "greek taverna lounge ambient",
            "aegean sea chill music",
            "mediterranean summer night music",
            "ethnic lounge chill mix 2026",
            "istanbul rooftop lounge music",
            "mediterranean villa ambient music",
            "greek summer lounge beats",
            "mediterranean ethnic fusion chill",
            "cyprus sunset lounge music",
            "mediterranean coast ambient mix",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "CormorantGaramond-Bold.ttf",
        "thumbnail_texts": ["Mediterranean", "Solstice", "Aegean Chill", "Greek Vibes", "Sunset Lounge"],
        "short_sentences": [
            "Aegean breeze. Olive trees. This track.",
            "Slow down. Mediterranean demands it.",
            "Blue and white. Sun and sound.",
            "Ancient light meets modern rhythm.",
            "The best talks happen after sunset.",
            "Opa. Volume up.",
            "Mediterranean time is the only time.",
            "Your table has a view. Ears have this.",
        ],
        "short_quotes": [
            "Mediterranean: beginning of everything.",
            "Strange towns. Best sensations. — Stark",
            "Travel brings new vigor. — Seneca",
        ],
        "long_video_comments": [
            "🫒 Aegean breeze. Olive trees. This mix. Drop a 🌊 if you're already there in your mind.",
            "🌅 The Mediterranean doesn't rush. Neither should you. Slow down with this 1-hour mix.",
            "🫒 Blue and white. Sun and sound. Ancient light meets modern rhythm. That's this channel.",
            "🌅 Santorini didn't come to you. But this music did. Close your eyes and go there.",
            "🌊 Drop a 🫒 if Mediterranean music is your idea of a perfect evening soundtrack.",
            "🫒 The best conversations happen after sunset. This mix sets that scene perfectly.",
            "🌅 Somewhere between Athens and Mykonos, you got wonderfully lost. This is that feeling.",
            "🫒 Opa. Volume up. Let the ethnic lounge energy of the Aegean wash over you.",
            "🌊 Comment your favorite Mediterranean destination below — Greece, Italy, Turkey, or Morocco?",
            "🫒 Mediterranean time is the only timezone that matters. This mix runs on that clock.",
            "🌅 Ancient light meets modern rhythm. That's the magic of Mediterranean music.",
            "🫒 Your table has a view. Your ears have this mix. The evening is complete.",
            "🌊 Drop a 🌅 if this music made you want to book a ticket to the Greek islands right now.",
            "🫒 Even the olive trees are dancing. That's how good this mix is.",
            "🌅 The Aegean sea has a frequency. This music captures it perfectly for 1 full hour.",
            "🫒 Summer solstice. Greek islands. Ethnic lounge. The perfect combination.",
            "🌊 Slow down. The Mediterranean demands it. And honestly? So do you.",
            "🫒 From Istanbul rooftops to Santorini sunsets — this mix takes you everywhere.",
            "🌅 Ancient culture. Modern beats. Timeless feeling. That's Mediterranean Solstice.",
            "🫒 The best summers always have a soundtrack. Let this mix be yours.",
        ],
        "short_video_comments": [
            "🫒 Full 1-hour mix on our channel. Mediterranean vibes.",
            "🌅 Greek island energy. Full version ↑",
            "🌊 Aegean chill. Full mix on our channel.",
            "🫒 Slow down. Full 1-hour version above.",
            "🌅 Ethnic lounge. Full mix on our channel.",
            "🌊 Full Mediterranean mix ↑ on our channel.",
            "🫒 Santorini sunset. Full version on our channel.",
            "🌅 1 hour of this. Full mix above.",
            "🌊 Ancient rhythm. Full mix on our channel.",
            "🫒 Opa. Full 1-hour version ↑",
            "🌅 Summer solstice sounds. Full mix on our channel.",
            "🌊 Full Greek session above.",
            "🫒 Blue and white. Full mix on our channel.",
            "🌅 Mykonos energy. Full version ↑",
            "🌊 Olive trees dancing. Full mix on our channel.",
            "🫒 Full Aegean session above.",
            "🌅 Istanbul rooftop. Full mix on our channel.",
            "🌊 Full ethnic lounge ↑",
            "🫒 Mediterranean time. Full mix on our channel.",
            "🌅 Full solstice mix above.",
        ],
    },
    "rain": {
        "display_name": "Urban Rain Vibes",
        "channel_id": "UCGXdnwMIJ2HCn3FfUm6NWKw",
        "drive_folder_id": "1JqJKwezAdBJd-7jycvMBvc8GVobwJU1c",
        "clips_folder_id": "17250ljI8QuflenzeJLzi2sp1z5zsBmYu",
        "drive_account": "hesap100",
        "youtube_account": "hesap100",
        "concept": "urban rain chill beats city ambience",
        "crossfade_seconds": 4,
        "video_keywords": ["rain music", "city rain ambience", "urban chill", "rainy day beats", "rain lofi"],
        "seo_keywords": [
            "tokyo rain street ambience music",
            "new york rainy rooftop chill beats",
            "urban rain lofi 1 hour",
            "city rain sounds chill music",
            "rainy day lofi hip hop",
            "london rain cafe ambience music",
            "urban rain meditation relaxation",
            "paris rainy street lofi beats",
            "city rain sounds for sleep",
            "rainy city night chill music",
            "urban rain study music 1 hour",
            "city rain ambience focus music",
            "rainy tokyo lofi beats study",
            "urban rain sounds relaxation",
            "city rain night lofi mix",
        ],
        "thumbnail_style": "text",
        "thumbnail_font": "SpaceGrotesk-Bold.ttf",
        "thumbnail_texts": ["URBAN RAIN", "CITY VIBES", "RAINY NIGHT", "TOKYO RAIN", "CHILL RAIN"],
        "short_sentences": [
            "Rain on glass. Music in ears.",
            "Tokyo, 2 AM. You know this.",
            "Every raindrop: tiny percussion.",
            "Urban souls find peace in rain.",
            "Coffee. Window. Rain. Playlist.",
            "Gray skies. Warm sounds.",
            "Headphones in. World out. Rain on.",
            "Some playlists are made for rain.",
        ],
        "short_quotes": [
            "Sound of rain needs no translation. — Watts",
            "Rainy days: tea and a book. — Watterson",
            "Dance in the rain. — Greene",
        ],
        "long_video_comments": [
            "🌧️ Rain on glass. Music in ears. Mind at rest. Drop a ☔ if that's your current vibe.",
            "🏙️ Tokyo, 2 AM, rain on the window, this mix in your headphones. You know the feeling.",
            "🌧️ Every raindrop is a tiny percussion instrument. This mix lets you hear all of them.",
            "🏙️ Urban souls find peace in rain. If you're one of them, this channel is your home.",
            "☔ Drop a 🌧️ if a rainy day with good music is genuinely one of your favorite things.",
            "🌧️ Coffee. Window seat. Rain outside. This playlist. The perfect combination.",
            "🏙️ Gray skies. Warm sounds. That's the paradox of urban rain music and we love it.",
            "🌧️ Headphones in. World out. Rain on. That's all the instructions you need for this mix.",
            "🏙️ Comment your city below — what does rain sound like where you are?",
            "☔ Some playlists are made for sunshine. This one was built specifically for rain.",
            "🌧️ The city has a heartbeat. Rain makes it slower. This mix captures that perfectly.",
            "🏙️ Wet pavements reflect the neon. This mix reflects that same urban energy.",
            "🌧️ The best thinking happens on rainy days. Here's 1 hour to prove that theory.",
            "☔ Drop a 🏙️ if rain sounds help you focus, sleep, or just feel more alive.",
            "🌧️ There's something about rain that makes everything slower and better. This mix too.",
            "🏙️ From Tokyo streets to London cafes — urban rain sounds like this around the world.",
            "🌧️ Rain doesn't cancel plans. It creates better ones. Like listening to this for an hour.",
            "☔ The sound of rain needs no translation. Neither does this music. Just feel it.",
            "🌧️ For the night owls, the thinkers, and the rainy day lovers — this mix is yours.",
            "🏙️ 1 hour of urban rain ambience. The city is alive. So are you. Enjoy every minute.",
        ],
        "short_video_comments": [
            "🌧️ Full 1-hour rain mix on our channel. Stay cozy.",
            "🏙️ Tokyo rain vibes. Full version ↑",
            "☔ Urban chill. Full mix on our channel.",
            "🌧️ City rain sounds. Full 1-hour version above.",
            "🏙️ Rain mode. Full mix on our channel.",
            "☔ Full rain mix ↑ on our channel.",
            "🌧️ Gray skies. Full version on our channel.",
            "🏙️ 1 hour of rain. Full mix above.",
            "☔ Urban peace. Full mix on our channel.",
            "🌧️ Coffee and rain. Full 1-hour version ↑",
            "🏙️ City heartbeat. Full mix on our channel.",
            "☔ Full rain session above.",
            "🌧️ Headphones in. Full mix on our channel.",
            "🏙️ Neon reflections. Full version ↑",
            "☔ Rainy day focus. Full mix on our channel.",
            "🌧️ Full urban rain session above.",
            "🏙️ London rain. Full mix on our channel.",
            "☔ Full city rain ↑",
            "🌧️ Best thinking weather. Full mix on our channel.",
            "🏙️ Full rain mix above.",
        ],
    },
}

# Video süresi - minimum 1 saat, doğal bitiş için son şarkı tamamlanır
MIN_VIDEO_DURATION_SECONDS = 3600  # 60 dk minimum

# Geçici dosya klasörü
TEMP_DIR = "/tmp/youtube-bot"

# Kanal bazlı ton/stil ayarları (Gemini için, SEO yapısı kodda zorlanıyor)
CHANNEL_PROMPTS = {
    "coding": {
        "title_style": "Cozy, chill, study-focused tone. Use 1 emoji from: 🎵☕🌧️🌙. Modifier examples: '1 HOUR', 'DEEP FOCUS', '2 AM SESSION', 'NO ADS'.",
        "description_style": "Warm and inviting tone. Mention studying, coding, focus, productivity naturally. 3-4 sentences.",
    },
    "zen": {
        "title_style": "Spiritual, peaceful, descriptive tone. Use 1 emoji from: 🕉️🧘🌸🪷. Modifier examples: '1 HOUR', 'DEEP HEALING', 'INNER PEACE', 'STRESS RELIEF'.",
        "description_style": "Spiritual and grounding tone. Mention yoga, meditation, mindfulness, healing. 4-5 sentences with peaceful tone.",
    },
    "vault": {
        "title_style": "Aggressive, short, hard-hitting. Use 1 emoji from: 🔥💰⚡🐺. Modifier examples: 'GRINDSET', 'NO EXCUSES', 'LOCK IN', '1 HOUR'. ALL CAPS allowed for impact.",
        "description_style": "Short, punchy, motivational. Sigma/grindset language. 2-3 short intense sentences.",
    },
    "chakra": {
        "title_style": "Spiritual, frequency-focused, descriptive. Use 1 emoji from: ✨🔮💫🪷. Modifier examples: '1 HOUR', 'DEEP HEALING', 'MANIFEST', 'CLEANSE'.",
        "description_style": "Mystical and healing tone. Mention specific chakras, frequencies (Hz), benefits. 4-5 sentences.",
    },
    "beach": {
        "title_style": "Fun, summery, party energy. Use 1 emoji from: 🌴☀️🏖️🍹🌊. Modifier examples: '2026', 'SUMMER MIX', 'POOL PARTY', '1 HOUR'.",
        "description_style": "Energetic and bright tone. Mention summer, beach, vacation, party. 3-4 upbeat sentences.",
    },
    "summer": {
        "title_style": "Smooth, sophisticated, lounge feel. Use 1 emoji from: 🌅🍸🌊✨. Modifier examples: 'SUNSET MIX', 'GOLDEN HOUR', 'LUXURY', '1 HOUR'.",
        "description_style": "Refined and chill tone. Mediterranean, lounge, sunset, rooftop language. 3-4 sophisticated sentences.",
    },
    "pets": {
        "title_style": "Warm, caring, problem-solving tone. Use 1 emoji from: 🐾🐶🐱🦮. Modifier examples: '1 HOUR', 'VET APPROVED', 'CALMING', 'PROVEN'.",
        "description_style": "Caring and helpful tone. Mention pet anxiety, separation, calming, vet-recommended. 4-5 warm sentences.",
    },
    "breathe": {
        "title_style": "Calm, sleep-focused, healing tone. Use 1 emoji from: 😴💤🌙🫁. Modifier examples: 'GUIDED', 'DEEP SLEEP', 'ANXIETY RELIEF', '1 HOUR'.",
        "description_style": "Soft and reassuring tone. Mention sleep, anxiety, breathing techniques, relaxation. 4-5 gentle sentences.",
    },
    "cosmic": {
        "title_style": "Dreamy, cosmic, space-focused tone. Use 1 emoji from: 🌌🚀⭐🪐. Modifier examples: '1 HOUR', 'DEEP SPACE', 'COSMIC CHILL', 'GALAXY VIBES'.",
        "description_style": "Mystical and expansive tone. Mention space, galaxies, cosmos, universe, stars. 3-4 sentences.",
    },
    "ocean": {
        "title_style": "Deep, calm, oceanic tone. Use 1 emoji from: 🌊🐋🌙💙. Modifier examples: '1 HOUR', 'DEEP OCEAN', 'WHALE SONGS', 'SLEEP MUSIC'.",
        "description_style": "Peaceful and deep tone. Mention ocean, whales, underwater, sleep, relaxation. 4-5 sentences.",
    },
    "mediterranean": {
        "title_style": "Warm, ethnic, sophisticated tone. Use 1 emoji from: 🌅🫒🌊☀️. Modifier examples: 'SUNSET MIX', 'SOLSTICE', 'GREEK VIBES', '1 HOUR'.",
        "description_style": "Warm and cultural tone. Mention Mediterranean, Greek islands, Aegean, summer, lounge. 3-4 sentences.",
    },
    "rain": {
        "title_style": "Cozy, urban, atmospheric tone. Use 1 emoji from: 🌧️🏙️☔🎵. Modifier examples: '1 HOUR', 'TOKYO RAIN', 'CITY VIBES', 'RAINY NIGHT'.",
        "description_style": "Cozy and atmospheric tone. Mention city rain, urban sounds, relaxation, chill. 3-4 sentences.",
    },
}
